# Generated by Django 5.1.4 on 2024-12-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('public', 'published')], default='Draft', max_length=256),
        ),
    ]
