# Generated by Django 5.1.4 on 2025-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'published')], default='Draft', max_length=256),
        ),
    ]
